### ISSUE TITLE
Help with running Selenium (Watir) to drive Chrome on Heroku, and click links

### ISSUE THREAD

**Issue by hemaldev** [jormon/minimal-chrome-on-heroku#1]
Hi @jormon, 

I've been scouting out how to do the above online for the last few days and have seen your links to this repo and the one for cedar-14.

We're running on heroku-16 and want to run some Watir scripts to drive a headless Chrome (essentially do some CRUD on some websites which don't have an API). We've got Chrome installing, opening and the script running, but now Selenium(/Watir) isn't finding elements on the page, which it does locally. 

We ready somewhere about it being troublesome for headless Chrome on heroku-16 to do normal things... and we're not sure what to try next. Ideally we'd like to stick with heroku-16.

We were wondering if you had any pointers for getting Selenium/Watir/headless Chrome to play nicely together on Heroku.

Thanks in advance.

**Comment by jormon** [comment]
Sorry for chiming in late, just saw this.

I haven't had any issues with compatibility between my local box (macOS) and heroku on heroku-16 and my scraping is fairly convoluted (goes beyond simple CRUD).

In terms of finding elements -- are you sure it's not finding the, or is Watir/Selenium refusing to click on them because they're not visible? ([background info](https://leanpub.com/watirways/read#leanpub-auto-unknownobjectexception---unable-to-locate-element))

To the extent that you can make your tests fail with a debugger, you can use `heroku bash` to poke around a live instance and query what exactly is going on on the page.

**Comment by hemaldev** [comment]
@jormon Thanks for the tips – will take a deeper look
